// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYFTk4nPvpVD_dKgnF9UWpHW7HIivMXU',
    appId: '1:421757948599:web:fa6ce062e1c5443f653332',
    messagingSenderId: '421757948599',
    projectId: 'appmess-41bfb',
    authDomain: 'appmess-41bfb.firebaseapp.com',
    storageBucket: 'appmess-41bfb.appspot.com',
    measurementId: 'G-PGT45TFZ1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDU73roHmsNrRTjTbXN-kSHtlt_oCRe4',
    appId: '1:421757948599:android:25ccfc03e72aba6e653332',
    messagingSenderId: '421757948599',
    projectId: 'appmess-41bfb',
    storageBucket: 'appmess-41bfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa152t33dwBouRyMHT9b922YHTxsXEqAo',
    appId: '1:421757948599:ios:8e3d22a439c58150653332',
    messagingSenderId: '421757948599',
    projectId: 'appmess-41bfb',
    storageBucket: 'appmess-41bfb.appspot.com',
    iosClientId: '421757948599-rj5rgdar4pfn2egu85d0hpjnolfbo31n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa152t33dwBouRyMHT9b922YHTxsXEqAo',
    appId: '1:421757948599:ios:8e3d22a439c58150653332',
    messagingSenderId: '421757948599',
    projectId: 'appmess-41bfb',
    storageBucket: 'appmess-41bfb.appspot.com',
    iosClientId: '421757948599-rj5rgdar4pfn2egu85d0hpjnolfbo31n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmess',
  );
}
